LuckPerms/LuckPerms

common/src/main/java/me/lucko/luckperms/commands/migration/subcommands/MigrationPermissionsEx.java
This allows prefixes and suffixes of group to migrate from PEX as well as player specifics using the maximum group weight.
=> PEX migration carries weights of prefixes/suffixes of groups and individuals

common/src/main/java/me/lucko/luckperms/commands/migration/subcommands/MigrationPermissionsEx.java
PermissionsEx negated/false nodes begin with a '-' not a '!'. This PR will fix the PEX migration process. [Source](https://github.com/PEXPlugins/PermissionsEx/wiki/Basic-Permissions-Setup#permission-nodes-top)
=> Fix PermissionsEx false node migration

common/src/main/java/me/lucko/luckperms/common/storage/backing/MySQLBacking.java
this commit further helps tame the mysql connection pool (and really
reconnecting to the pool even when the underlying db goes down) further
from commit: 31a597c
helps in the case of #81 
this sets up `setValidationTimeout`, and `setConnectionTestQuery`
in order to better (more speedily(?)/fastly(?)/<other adective>ly(?))
handle connection timeouts in a timely manner. (although admittedly
this is already handeled well imo with the cache). however, it could
be better :tm:.
in order to do this I did the following things:
1. Switch to `TimeUnit.SECONDS.toMillis` instead of manually entering
milliseconds, and having the time in seconds as a comment. just
makes it more readable imo. if you want me to change it back I can
I'm not like attached to this or anything.
2. Perform more common …
=> help tame mysql connection settings

common/src/main/java/me/lucko/luckperms/common/core/model/PermissionHolder.java
The old permission wasn't being removed if it was specific to a particular world or server.
=> Fix accumulation of temporary perms with a world or server context

common/src/main/java/me/lucko/luckperms/common/bulkupdate/BulkUpdate.java
[StackOverflow - What is the difference between single and double quotes in SQL?](https://stackoverflow.com/questions/1992314/what-is-the-difference-between-single-and-double-quotes-in-sql)
It was causing errors like `org.h2.jdbc.JdbcSQLException: Column "someperm" not found; SQL statement: DELETE FROM luckperms_group_permissions WHERE permission = "someperm";`
=> Use single quotes in escapeStringForSql

common/src/main/java/me/lucko/luckperms/common/storage/dao/sql/SqlDao.java
The absence of an explicit indication of the column names leads to some problems. In particular, this happens when using ORM, in which it is inconvenient to specify the order of the columns.
=> Added explicit column names in INSERT queries.

common/src/main/java/me/lucko/luckperms/common/model/Group.java
This fixes issues with the colors leaking from a group name into messages after the name if it's colored and doesn't end with a reset. Coloring both, the first and the last parentheses makes it look nicer and easier to see if the display name was colored or not (white is mostly associated with not colored at all)
=> Use neutral color to display potentially colored names (Fixes #1170)

nukkit/src/main/java/me/lucko/luckperms/nukkit/model/permissible/LPPermissible.java
It's valid for null to be passed, it's not a FAWE bug...
https://github.com/NukkitX/Nukkit/blob/master/src/main/java/cn/nukkit/Player.java#L505
=> Fixes #1191

common/src/main/java/me/lucko/luckperms/common/locale/command/CommandSpec.java
Fixed up a typo on line 95 
"Exports all permissions data to an 'export' file. Be be re-imported at a later time."
TO
"Exports all permissions data to an 'export' file. Can be re-imported at a later time."
=> Fix Typo with /export 

bukkit/src/main/resources/config.yml, bungee/src/main/resources/config.yml, nukkit/src/main/resources/config.yml, sponge/src/main/resources/luckperms.conf, velocity/src/main/resources/config.yml
The LuckPerms configs contain a description of the messaging services you can use.
Those are partially confusing and maybe even misleading.
For example does the description of `none` state that it...
> Disables the service.
...while `sql` says the following information:
> Uses the SQL database to form a queue system for communication. Will only work when 'storage-method' is set to MySQL or MariaDB. **This is chosen by default if the option is set to 'none' and SQL storage is in use. Set to 'notsql' to disable this.**
This PR adds a bit more description about how `none` works in certain situations and also lists and explains the `notsql` option since according to the description of sql is this a valid and available option which shouldn't be kept secret.
=> Update config description of messaging service

bukkit/src/main/resources/config.yml, bungee/src/main/resources/config.yml, nukkit/src/main/resources/config.yml, sponge/src/main/resources/luckperms.conf, velocity/src/main/resources/config.yml
The link to [Storage types](https://github.com/lucko/LuckPerms/wiki/Storage-types) seemed to be outdated
=> Fix the link to Storage types comparison

common/src/main/java/me/lucko/luckperms/common/backup/Exporter.java, common/src/main/java/me/lucko/luckperms/common/commands/misc/ExportCommand.java, common/src/main/java/me/lucko/luckperms/common/commands/misc/ImportCommand.java, common/src/main/java/me/lucko/luckperms/common/locale/message/Message.java
Allows users to export to bytebin instead of saving to file.
- `/lp export --upload` - returns the 10 digit bytebin code
- `/lp import <code> --upload`
A couple things to note:
- It does not perform any checks on the import to see if the JSON is formed correctly, I'm not sure if this is handled by the Importer class already.
- There is no way to copy the code, which may be annoying to some users. I considered letting users click a link for the bytebin upload but IMO it seems unnecessary.
Let me know if there is anything that should be changed. I'm not very comfortable using Java so there will likely be things that can be done better :P
=> Add option to use bytebin for exports/imports

common/src/main/java/me/lucko/luckperms/common/locale/Message.java, common/src/main/java/me/lucko/luckperms/common/storage/implementation/mongodb/MongoStorage.java, common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/connection/hikari/HikariConnectionFactory.java
- Fixes legacy `&a` in ping indicator for remote DBs in `/lp info` (#2670)
- Returns the prefix back to it's old Aqua/Dark Aqua
=> Fix formatting issues

common/src/main/java/me/lucko/luckperms/common/bulkupdate/BulkUpdate.java, common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/SqlStorage.java
Fixes a bug for the bulk update command failing on SQL based storages when tracking operation stats with multiple constraints, making the "impact lookup" query `... WHERE field1 = 'value1'field2 = 'value2'field3 = 'value3' ...`
=> Fix bulk update SQL stats lookup bug

bukkit/src/main/java/me/lucko/luckperms/bukkit/BukkitConfigAdapter.java
Hi again! :)
**Change**
Configuration#getStringList(String) does never return null. Instead it returns a new list if one is absent from the file. This means that the fallback list will never be returned or used regardless. A change to make this work would be to return the fallback list if and only if Configuration#isSet(String) returns false. While we could use Configuration#isString(String) or Configuration#isList(String) both of them are quite pedantic. Let alone Configuration#getStringList(String) would convert a single config value to a singleton list. It would also convert a list of numbers to a list of strings. In conclusion Configuration#isSet(String) would be the only mandatory check required.
=> Substitute null check with Configuration#isSet

common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/SqlStorage.java
Fixes #2842, #2774, and a number of duplicate issues where LP would not create the database tables even though it would connect properly (additionally, creating and leaving the `{prefix}messenger` table as the only table on the database); issue is it was scanning through the entirety of the sql server, so if another database on the same server already had the `{prefix}user_permissions` table, it would return true. Fixed by passing the catalog (essentially the db name) to the getTables query as "filter".
Tested on MariaDB and MySQL.
=> Fix millenary issue on SQL storage systems

bukkit/src/main/java/me/lucko/luckperms/bukkit/listeners/BukkitConnectionListener.java
Lately on the discord server I've noticed a number of CraftBukkit + offline mode server logs that LP wasn't detecting as CraftBukkit (but CB being CB it still [doesn't call APPLE](https://hub.spigotmc.org/jira/browse/SPIGOT-3541)), to then find out recent CB builds don't show the version as `git-Bukkit-<short sha1> ...` but `<some number?>-Bukkit-<short sha1> ...`; this PR fixes that, tested on both old and new CB builds.
=> Improve CraftBukkit detection

bukkit/src/main/resources/config.yml, bungee/src/main/resources/config.yml, common/src/main/java/me/lucko/luckperms/common/config/ConfigKeys.java, common/src/main/java/me/lucko/luckperms/common/messaging/MessagingFactory.java, common/src/main/java/me/lucko/luckperms/common/messaging/rabbitmq/RabbitMQMessenger.java, fabric/src/main/resources/luckperms.conf, nukkit/src/main/resources/config.yml, sponge/src/main/resources/luckperms.conf, velocity/src/main/resources/config.yml
Tested on latest BungeeCord (`git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:3d701fb:1545`), no reason why it wouldn't work on any other system since the configs follow the format I found in them, and this is all in common rather than implementations. I will happily test it on all systems though on request.
Virtual hosts are used to split up things into different things basically (I'm not very good with explanations, see [here](https://www.rabbitmq.com/vhosts.html)), which allows you to isolate all your different projects that use it, so there's no interference.
=> Added virtual host support for RabbitMQ

common/src/main/java/me/lucko/luckperms/common/locale/Message.java
Inherited meta nodes would show "Click to remove ... from \<holder\>" where \<holder\> would be the holder the command was run on, not the original meta node holder. This would often cause confusion when trying to delete the clicked node when inherited.
=> Fix holder type and name on hover and click events in meta info entries

common/src/main/java/me/lucko/luckperms/common/event/gen/GeneratedEventClass.java
When using Mohist 1.16 (and maybe other Forge+Bukkit hybrids), GeneratedEventClass.class.getPackage() is null for whatever reason.
This tiny change implements another way of getting the package and restores
compatibility with Mohist & Co.
=> Safer way of getting GeneratedEventClass package

fabric/src/main/java/me/lucko/luckperms/fabric/context/FabricPlayerCalculator.java
When testing with Fabric for 1.17-rc1, this exception occurred when a player joins:
```
[Server thread/WARN]: An exception was thrown by me.lucko.luckperms.fabric.context.FabricPlayerCalculator whilst
calculating the context of subject class_3222['****'/150, l='ServerLevel[world]', x=-33.75, y=68.00, z=-18.60]
java.lang.NoSuchFieldError: field_9218
at me.lucko.luckperms.fabric.context.FabricPlayerCalculator.calculate(FabricPlayerCalculator.java:78) ~[LuckPerms-Fabric-5.3.42.jar:?]
at me.lucko.luckperms.fabric.context.FabricPlayerCalculator.calculate(FabricPlayerCalculator.java:52) ~[LuckPerms-Fabric-5.3.42.jar:?]
at me.lucko.luckperms.common.context.ContextManager.calculate(ContextManager.java:131) ~[LuckPerms-Fabric-5.3.42.jar:?]
```
This is because the enum value `GameMode.NOT_SET` was …
=> Fabric - Compatibility with 1.17

fabric/src/main/java/me/lucko/luckperms/fabric/LPFabricPlugin.java, fabric/src/main/java/me/lucko/luckperms/fabric/context/FabricPlayerCalculator.java, fabric/src/main/java/me/lucko/luckperms/fabric/listeners/FabricCommandListUpdater.java
Update the list of commands sent to the client when permissions are changed.
Makes the `update-client-command-list = true` config option functional for Fabric like Bukkit.
Fixes https://github.com/TjeuKayim/minecraft-command-permissions-fabric/issues/2
=> Implement command list updater for Fabric

common/src/main/java/me/lucko/luckperms/common/command/utils/StorageAssistant.java, common/src/main/java/me/lucko/luckperms/common/commands/group/GroupRename.java
When using the newly introduced `--update-parent-lists` flag in the group rename command, it had the catastrophically undesired side effect of refreshing the new/renamed group from storage, discarding **every** permission that was added after the group creation.
The primary change is really in GroupRename, but to ensure that the bulk operation + syncing happens *after* the group is saved, I ended up adapting the StorageAdapter to return the messaging service request's future for continuation purposes.
=> Group rename - Save renamed group before syncing with storage

bukkit/src/main/resources/config.yml, fabric/src/main/resources/luckperms.conf, nukkit/src/main/resources/config.yml
If you deactivate operator via LP, you have side effects with basic vanilla features. I add a small note in the config about that.
=> adding note about required operator

bukkit/src/main/resources/config.yml, bungee/src/main/resources/config.yml, common/src/main/java/me/lucko/luckperms/common/config/ConfigKeys.java, common/src/main/java/me/lucko/luckperms/common/messaging/MessagingFactory.java, common/src/main/java/me/lucko/luckperms/common/messaging/redis/RedisMessenger.java, fabric/src/main/resources/luckperms.conf, nukkit/src/main/resources/config.yml, sponge/src/main/resources/luckperms.conf, velocity/src/main/resources/config.yml
Hi!
I'm going straight to the point: the current version of LuckPerms has just a password field for Redis authentication which limits the setup to a default username auth system which not always is the best option for security purposes. Then I decided to open this pull request to implement an optional username field which enables the authentication through username too. I have tried the new feature before opening this PR to test it and everything seems working correctly.
=> Added redis authentication with username

bukkit/src/main/java/me/lucko/luckperms/bukkit/vault/AbstractVaultPermission.java, bukkit/src/main/java/me/lucko/luckperms/bukkit/vault/LuckPermsVaultPermission.java
As per this [issue](https://github.com/LuckPerms/LuckPerms/issues/3238) I have added the missing methods that the Vault API does wrong and implemented them to use the transient Node on the user's Permission Holder.
=> Added full support for tansient permissions through Vault API

common/src/main/java/me/lucko/luckperms/common/commands/group/GroupInfo.java, common/src/main/java/me/lucko/luckperms/common/commands/user/UserInfo.java
Reworks the `GroupInfo` and `UserInfo` commands' method of resolving permanent and temporary parent nodes.
Uses Java 8's "Grouping By" collector to group the nodes into a map of results, rather than executing the entire operation twice with a different filter.
*(i would actually have loved to have this operation be generic and reusable outside of these commands, but I don't see where things like that are stored in the project, so duplicate code is fine for now ig)*
=> Optimize parent resolution in info commands

forge/src/main/java/me/lucko/luckperms/forge/service/ForgePermissionHandler.java
Current implementation never have a chance to use Forge's default resolver for BOOLEAN permissions and I guess it is not an intended behaviour.
=> Use forge default resolver when result is undefined

forge/gradle.properties, forge/loader/src/main/resources/META-INF/mods.toml, forge/loader/src/main/resources/pack.mcmeta, forge/src/main/java/me/lucko/luckperms/forge/listeners/ForgeConnectionListener.java
This PR updates the Forge platform to 1.19
The `LOADING_STATE_ERROR` message sent during `onPlayerNegotiationAsync` has been removed as it's already being sent during the `onPlayerLoadFromFile` event.
=> Forge 1.19

forge/src/main/java/me/lucko/luckperms/forge/capabilities/UserCapabilityListener.java
Current implementation do not clone capability when teleport from the end to overworld with end portal, causing the capability not initialised:
<details>
<pre>
[13:17:39 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundClientCommandPacket@64b9ed37, suppressing error
java.lang.IllegalStateException: Capability has not been initialised
at me.lucko.luckperms.forge.capabilities.UserCapabilityImpl.assertInitialised(UserCapabilityImpl.java:95) ~[?:?]
at me.lucko.luckperms.forge.capabilities.UserCapabilityImpl.checkPermission(UserCapabilityImpl.java:101) ~[?:?]
at me.lucko.luckperms.forge.util.BrigadierInjector$InjectedPermissionRequirement.test(BrigadierInjector.java:146) ~[?:?]
at me.lucko.luckperms.forge.util.BrigadierInjector$InjectedPermissionRequirement.test(Br …
=> Fix forge capability not cloned when returning from the end

common/src/main/java/me/lucko/luckperms/common/plugin/classpath/URLClassLoaderAccess.java
I had issues using ReflectionAppender with concurrency, so adding synchronized fixes it.
=> Fix concurrent errors with unopenedURLs

bukkit-legacy/build.gradle, bukkit/build.gradle, bukkit/src/main/resources/config.yml, bungee/build.gradle, bungee/src/main/resources/config.yml, common/build.gradle, common/src/main/java/me/lucko/luckperms/common/config/ConfigKeys.java, common/src/main/java/me/lucko/luckperms/common/dependencies/Dependency.java, common/src/main/java/me/lucko/luckperms/common/dependencies/DependencyManager.java, common/src/main/java/me/lucko/luckperms/common/dependencies/DependencyRegistry.java, common/src/main/java/me/lucko/luckperms/common/messaging/MessagingFactory.java, common/src/main/java/me/lucko/luckperms/common/messaging/nats/NatsMessenger.java, common/src/main/java/me/lucko/luckperms/common/plugin/AbstractLuckPermsPlugin.java, fabric/build.gradle, fabric/src/main/resources/luckperms.conf, forge/build.gradle, nukkit/build.gradle, nukkit/src/main/resources/config.yml, sponge/build.gradle, sponge/src/main/resources/luckperms.conf, standalone/build.gradle, standalone/src/main/resources/config.yml, velocity/build.gradle, velocity/src/main/resources/config.yml
Adds [nats](https://nats.io/) implementation to LuckPerms messaging system.
also, removes message about loading and not recognizing messenger when it is set to `custom`.
=> Adding Nats messenger implementation to LuckPerms

fabric/src/main/java/me/lucko/luckperms/fabric/listeners/FabricConnectionListener.java
The offline profile is created inside the `ServerLoginNetworkHandler.acceptPlayer()` method, which is called after handling the Fabric's `ServerLoginConnectionEvents.QUERY_START` event.
Fixes #3564, fixes #3574, fixes #3573
=> Restore offline mode support for Fabric servers

common/src/main/java/me/lucko/luckperms/common/commands/misc/VerboseCommand.java
This led to some confusion today on the docs and it was settled that it would be easiest to just add this in as a tab completion.
=> Add in paste to the tab completions for verbose

forge/src/main/java/me/lucko/luckperms/forge/capabilities/UserCapabilityListener.java
This PR addresses player data being corrupted if exception was thrown during `PlayerEvent.Clone`.
=> Fix player data being corrupted on respawn. (#3557, #3584, #3596)

common/src/main/java/me/lucko/luckperms/common/dependencies/DependencyManager.java, common/src/main/java/me/lucko/luckperms/common/dependencies/relocation/RelocationHandler.java, common/src/main/java/me/lucko/luckperms/common/plugin/AbstractLuckPermsPlugin.java
Close the isolated loaders for dependencies that are not relocated (H2/SQLite drivers, ASM, JAR relocator etc) on disable.
=> Cleanup loaders on shutdown

common/src/main/java/me/lucko/luckperms/common/locale/Message.java, common/src/main/resources/luckperms_en.properties
This closes #3408.
On hover message on the currently displayed time since ago the full date and time is shown.
This is my first PR so please let me know if I have missed anything!
=> Add date on hover to log

common/src/main/java/me/lucko/luckperms/common/dependencies/Dependency.java, common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/connection/hikari/HikariConnectionFactory.java, common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/connection/hikari/MariaDbConnectionFactory.java, common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/connection/hikari/MySqlConnectionFactory.java, standalone/build.gradle, standalone/src/test/java/me/lucko/luckperms/standalone/MessagingIntegrationTest.java
In older versions of the driver (before 3.1.0?) there is a bug, in newer versions I have not noticed it
(litebans uses 3.0.7)
=> Update mariadb jdbc driver to 3.1.2

fabric/src/main/java/me/lucko/luckperms/fabric/FabricSenderFactory.java, fabric/src/main/java/me/lucko/luckperms/fabric/mixin/ServerCommandSourceAccessor.java, fabric/src/main/resources/luckperms.mixins.json, forge/src/main/java/me/lucko/luckperms/forge/ForgeSenderFactory.java
The fabric console detection currently simply checks if the `ServerCommandSource` has an entity "attached".
However, this causes two problems:
1. The execute command can attach entities to the command source, eg: `/execute as @a run lp user @s parent add player`. When this command is executed from the console, only players with permission to run `lp user @s parent add player` will receive the group. The version info message is printed into the console for any other player. Allowing modifiers like this allows for better datapack integration with luckperms commands. 
2. There is currently a small security issue. It is currently possible to run any luckperms commands as an OP player, by using a command block to execute them (because that doesn't have an entity attached), even though OP …
=> Improve "console" detection on fabric

bukkit/src/main/resources/config.yml, bungee/src/main/resources/config.yml, common/build.gradle, common/src/main/java/me/lucko/luckperms/common/config/ConfigKeys.java, common/src/main/java/me/lucko/luckperms/common/config/generic/key/ConfigKeyFactory.java, common/src/main/java/me/lucko/luckperms/common/dependencies/Dependency.java, common/src/main/java/me/lucko/luckperms/common/messaging/MessagingFactory.java, common/src/main/java/me/lucko/luckperms/common/messaging/redis/RedisMessenger.java, fabric/src/main/resources/luckperms.conf, forge/src/main/resources/luckperms.conf, nukkit/src/main/resources/config.yml, sponge/src/main/resources/luckperms.conf, standalone/build.gradle, standalone/src/main/resources/config.yml, velocity/src/main/resources/config.yml
I once expanded the Redis support so that you can also use messaging with a Redis cluster.
I only made `addresses` from the `adress` in the config and a string list where you can specify the IP addresses and ports of your Redis nodes.
=> Add support for redis cluster

CONTRIBUTING.md, README.md, bukkit/src/main/java/me/lucko/luckperms/bukkit/LPBukkitPlugin.java, bukkit/src/main/resources/config.yml, bungee/src/main/resources/config.yml, common/src/main/java/me/lucko/luckperms/common/plugin/AbstractLuckPermsPlugin.java, common/src/main/java/me/lucko/luckperms/common/util/UniqueIdType.java, fabric/src/main/resources/fabric.mod.json, fabric/src/main/resources/luckperms.conf, forge/src/main/resources/luckperms.conf, nukkit/src/main/java/me/lucko/luckperms/nukkit/inject/permissible/PermissibleInjector.java, nukkit/src/main/java/me/lucko/luckperms/nukkit/listeners/NukkitConnectionListener.java, nukkit/src/main/resources/config.yml, sponge/src/main/resources/luckperms.conf, standalone/src/main/resources/config.yml, velocity/src/main/resources/config.yml
Just a simple find and replace for `https://github.com/lucko/LuckPerms` to `https://github.com/LuckPerms/LuckPerms`. :)
=> Update Github links to LuckPerms/LuckPerms

bukkit/src/main/resources/config.yml, fabric/src/main/resources/luckperms.conf, forge/src/main/resources/luckperms.conf, sponge/src/main/resources/luckperms.conf
The Minecraft Wiki maintainers have decided to move away from Fandom. More information can be found here: https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom. This PR updates all the URLs to the new domain: minecraft.wiki
Also updates the URL since the resource was moved on the Minecraft Wiki
=> Update Minecraft Wiki links to new domain after fork

bukkit/src/main/java/me/lucko/luckperms/bukkit/listeners/BukkitPlatformListener.java
Ran a spark profile the other day and noticed luckperms was the highest tick consuming plugin (still very minimal) but this change should help with that. https://imgur.com/LxnTEAJ
=> tiny performance tweak

common/src/main/java/me/lucko/luckperms/common/config/ConfigKeys.java, common/src/main/java/me/lucko/luckperms/common/config/generic/adapter/EnvironmentVariableConfigAdapter.java, common/src/main/java/me/lucko/luckperms/common/config/generic/adapter/SystemPropertyConfigAdapter.java
Tested with system properties, I assume it'll also work for environmental variables
Closes #3807
=> Fix environmental/property credentials leaking

api/src/main/java/net/luckperms/api/track/TrackManager.java, common/src/main/java/me/lucko/luckperms/common/api/implementation/ApiTrackManager.java
The UserManager and GroupManager both have a convenience method for loading and saving a user or a group after applying a modification. The TrackManager lacks this operation, despite also being modifiable and needing to be saved. I see this as a small hole in the API.
This PR adds a modifyTrack method to TrackManager, very closely modeled after modifyGroup.
I am making this PR because I found myself wanting this method, and it provides symmetry in the API.
=> Add modifyTrack to TrackManager

common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/SqlStorage.java
After analyzing the code on the SqlStorage, I found that line of code when selecting user permission nodes.
After checking again, I came to the conclusion that reading the node again was unnecessary and wouldn’t affect the behavior.
=> Don’t read permission nodes twice for users

common/src/main/java/me/lucko/luckperms/common/config/ConfigKeys.java
Fixes #3850.
Caused by this from I believe a previous luckperms config version? https://github.com/LuckPerms/LuckPerms/blob/8c6586f008fb567a0b396df2b0fbc3c7093441d5/common/src/main/java/me/lucko/luckperms/common/config/ConfigKeys.java#L580
Another fix could be to remove the old config path
=> fix: Environmental variables logging mongodb secrets

bukkit/loader/build.gradle
Remap is not needed since we don't use any non-reflection NMS (or NMS in general, afaik).
=> Set mappings namespace to skip remapping on Paper 1.20.5+

fabric/src/main/java/me/lucko/luckperms/fabric/context/FabricContextManager.java, fabric/src/main/java/me/lucko/luckperms/fabric/listeners/FabricConnectionListener.java, fabric/src/main/java/me/lucko/luckperms/fabric/listeners/FabricPermissionsApiListener.java, fabric/src/main/java/me/lucko/luckperms/fabric/mixin/ServerPlayerEntityMixin.java, fabric/src/main/java/me/lucko/luckperms/fabric/model/MixinUser.java
Respawning creates a new ServerPlayerEntity instance. The current code copies the QueryOptionsCache from the old player instance, however this causes an issue, because the cache still holds the reference to the old entity. So any usage of it will invoke ContextManager.calculate causing outdated context to be calculated. This is simply fixed by creating a new QueryOptionsCache with the new instance.
TLDR: Currently context changes are no longer updated (on fabric) after player deaths, this PR fixes this.
=> Fix QueryOptionsCache referencing outdated player instance

bukkit/src/main/java/me/lucko/luckperms/bukkit/context/BukkitContextManager.java, bukkit/src/main/java/me/lucko/luckperms/bukkit/inject/permissible/LuckPermsPermissible.java, bukkit/src/main/java/me/lucko/luckperms/bukkit/inject/permissible/PermissibleInjector.java, bukkit/src/main/java/me/lucko/luckperms/bukkit/listeners/BukkitConnectionListener.java, bungee/src/main/java/me/lucko/luckperms/bungee/context/BungeeContextManager.java, common/src/main/java/me/lucko/luckperms/common/context/manager/ContextManager.java, common/src/main/java/me/lucko/luckperms/common/context/manager/DetachedContextManager.java, common/src/main/java/me/lucko/luckperms/common/context/manager/QueryOptionsCache.java, common/src/main/java/me/lucko/luckperms/common/context/manager/QueryOptionsSupplier.java, common/src/main/java/me/lucko/luckperms/common/context/manager/SimpleContextManager.java, fabric/src/main/java/me/lucko/luckperms/fabric/context/FabricContextManager.java, fabric/src/main/java/me/lucko/luckperms/fabric/mixin/ServerPlayerEntityMixin.java, fabric/src/main/java/me/lucko/luckperms/fabric/model/MixinUser.java, forge/src/main/java/me/lucko/luckperms/forge/LPForgePlugin.java, forge/src/main/java/me/lucko/luckperms/forge/capabilities/UserCapabilityImpl.java, forge/src/main/java/me/lucko/luckperms/forge/capabilities/UserCapabilityListener.java, forge/src/main/java/me/lucko/luckperms/forge/context/ForgeContextManager.java, forge/src/main/java/me/lucko/luckperms/forge/listeners/ForgeConnectionListener.java, forge/src/main/java/me/lucko/luckperms/forge/service/ForgePermissionHandler.java, neoforge/src/main/java/me/lucko/luckperms/neoforge/context/NeoForgeContextManager.java, nukkit/src/main/java/me/lucko/luckperms/nukkit/context/NukkitContextManager.java, nukkit/src/main/java/me/lucko/luckperms/nukkit/inject/permissible/LuckPermsPermissible.java, nukkit/src/main/java/me/lucko/luckperms/nukkit/inject/permissible/PermissibleInjector.java, nukkit/src/main/java/me/lucko/luckperms/nukkit/listeners/NukkitConnectionListener.java, sponge/src/main/java/me/lucko/luckperms/sponge/context/SpongeContextManager.java, standalone/src/main/java/me/lucko/luckperms/standalone/stub/StandaloneContextManager.java, velocity/src/main/java/me/lucko/luckperms/velocity/context/VelocityContextManager.java, velocity/src/main/java/me/lucko/luckperms/velocity/listeners/VelocityConnectionListener.java, velocity/src/main/java/me/lucko/luckperms/velocity/service/PlayerPermissionProvider.java
Maybe a fix for #4049
In the past for some platforms, LuckPerms used a global map as a fallback for locating `QueryOptionsCache` instances - this has proven to be a bit brittle and potentially the cause of some memory leaks, although never confirmed.
I can't see anything specifically wrong in the old code, but using `Player` as the key in a map feels wrong and I have a feeling it is the cause of the issues observed in #4049.
=> Improve context manager caching

api/src/main/java/net/luckperms/api/node/types/DisplayNameNode.java, api/src/main/java/net/luckperms/api/node/types/InheritanceNode.java, api/src/main/java/net/luckperms/api/node/types/MetaNode.java, api/src/main/java/net/luckperms/api/node/types/PermissionNode.java, api/src/main/java/net/luckperms/api/node/types/RegexPermissionNode.java
#3606 has improved handling of empty inputs by `NodeBuilder`s, but forgot to add `IllegalArgumentException`s for static builder methods of node classes.
=> Add missing IllegalArgumentExceptions to Javadocs

common/build.gradle, common/src/main/java/me/lucko/luckperms/common/config/ConfigKeys.java, common/src/main/java/me/lucko/luckperms/common/node/matcher/StandardNodeMatchers.java, common/src/main/java/me/lucko/luckperms/common/storage/StorageFactory.java, common/src/main/java/me/lucko/luckperms/common/storage/StorageType.java, common/src/main/java/me/lucko/luckperms/common/storage/implementation/rest/RestStorage.java, common/src/test/java/me/lucko/luckperms/common/storage/RestStorageTest.java, standalone/build.gradle, standalone/src/test/java/me/lucko/luckperms/standalone/StorageIntegrationTest.java
Adds REST as a storage backend.
Typically in multi-server (network) setups, plugins share state by all connecting and reading/writing to the same database instance.
```mermaid
flowchart BT;
1[MC Server 1] --> D[(Database)]
2[MC Server 2] --> D
3[MC Server 3] --> D
4[MC Server 4] --> D
5[MC Server 5] --> D
6[MC Server 6] --> D
7[MC Server 7] --> D
8[MC Server 8] --> D
9[MC Server 9] --> D
```
An alternate setup, useful especially when running lots of individual MC server instances, would be to have only a few instances of LP connected directly to the database (labelled as 'LP REST' in the diagram below), with all other instances obtaining data via the REST API exposed on these instances. 
Benefits:
* fewer connections to the backend database
* possible to enable caching at the middle layer …
=> Add REST storage backend

fabric/src/main/java/me/lucko/luckperms/fabric/listeners/FabricConnectionListener.java
Tested and Fixed #3857.
The issue was caused by calling `this.plugin.getBootstrap().getScheduler().executeAsync` inside `handleDisconnect` when the server is shutting down. At this point, the scheduler is no longer available on Fabric, which leads to a `RejectedExecutionException`. Specifically, `MinecraftServer` throws `RejectedExecutionException("Server already shutting down")` when this code is executed.
This does not occur on other platforms (like Bukkit) because listeners are automatically unregistered during `onDisable`. However, Fabric has no `disable` concept and only provides `onInitializeServer` with `SERVER_STARTING` / `SERVER_STOPPING` events.
=> fix(fabric): prevent async task execution when stopping server
