bukkit/pom.xml
bukkit/src/main/java/me/lucko/luckperms/bukkit/migration/MigrationZPermissions.java

tested, should be safe to merge

Zpermimport

---

.locale/ru_RU.yml

Add ru_RU.yml

---

.locale/zh-CN.yml

Standardized translation and minor bug fixes

Update zh-CN locale

---

common/src/main/java/me/lucko/luckperms/common/dependencies/DependencyManager.java

Added uranium server support

---

bukkit/src/main/java/me/lucko/luckperms/bukkit/LPBukkitPlugin.java

Needed to change URL to reflect changes made via https://github.com/lucko/LuckPerms/commit/ea94bd8696f4b3be577e3766385b8a4f51a3f48a

Update location of LuckPermsLegacy

---

bukkit/src/main/resources/config.yml
bungee/src/main/resources/config.yml
common/src/main/java/me/lucko/luckperms/common/config/ConfigKeys.java
common/src/main/java/me/lucko/luckperms/common/storage/StorageFactory.java
common/src/main/java/me/lucko/luckperms/common/storage/dao/mongodb/MongoDao.java
nukkit/src/main/resources/config.yml
sponge/src/main/resources/luckperms.conf

[View the issue here](https://github.com/lucko/LuckPerms/issues/776)

MongoDB Replica Set connections cannot resolve (#776)

---

nukkit/src/main/java/me/lucko/luckperms/nukkit/NukkitCommandExecutor.java

Fixes #870 
It turns out that quotes are already taken into account by Nukkit.

Fixed command arguments for Nukkit

---

README.md

This calms my OCD 🙏 
I also changed the number to "a few" so it won't have to be changed again.

Fix a number in the README

---

CONTRIBUTING.md
bungee/src/main/resources/config.yml
velocity/src/main/resources/config.yml

Changes that where made:
- fixed typos in the description of `cancel-failed-logins:` (Changed from `of` to `or`)
- Updated information in the section `Project Layout` of the CONTRIBUTING.md (Added Velocity and Nukkit and made it look similar to the part in the README.md)

Fixing smaller typos and also outdated info in CONTRIBUTING.md

---

common/src/main/java/me/lucko/luckperms/common/cache/LoadingMap.java
common/src/main/java/me/lucko/luckperms/common/cache/PatternCache.java

Fix failing build on [ci](https://ci.lucko.me/job/LuckPerms/)

Fix failing build!

---

common/src/main/java/me/lucko/luckperms/common/messaging/sql/AbstractSqlMessenger.java

Escape table name with backticks (`) in sql messenger

---

common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/SqlStorage.java
common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/connection/file/H2ConnectionFactory.java
common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/connection/file/SQLiteConnectionFactory.java
common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/connection/hikari/PostgreConnectionFactory.java

Tested with MySQL, PostgreSQL, H2 and SQLite.
#1847

Additional fixes for #1847

---

bukkit/src/main/resources/config.yml
bungee/src/main/resources/config.yml
nukkit/src/main/resources/config.yml
sponge/src/main/resources/luckperms.conf
velocity/src/main/resources/config.yml

Make it faster&easier to deploy LP without annoying WARNINGS when using external DB storage.

Enhance default config (#2005)

---

bukkit/src/main/resources/config.yml
bungee/src/main/resources/config.yml
nukkit/src/main/resources/config.yml
sponge/src/main/resources/luckperms.conf
velocity/src/main/resources/config.yml

Expand the meta formatting section in the config files.
Closes #2090.

Expand meta formatting section

---

common/src/main/resources/me/lucko/luckperms/schema/h2.sql
common/src/main/resources/me/lucko/luckperms/schema/mariadb.sql
common/src/main/resources/me/lucko/luckperms/schema/mysql.sql
common/src/main/resources/me/lucko/luckperms/schema/postgresql.sql
common/src/main/resources/me/lucko/luckperms/schema/sqlite.sql

Increase world column max size

---

api/src/main/java/net/luckperms/api/query/QueryOptionsRegistry.java

Correct a typo in the API JavaDoc

Fix JavaDoc typo

---

common/src/main/java/me/lucko/luckperms/common/messaging/redis/RedisMessenger.java

Try to reopen Redis pub-sub connection on failure

---

common/src/main/java/me/lucko/luckperms/common/locale/Message.java

Format group info prefix and suffix

---

common/src/main/java/me/lucko/luckperms/common/commands/generic/meta/MetaSetTemp.java

This does not check for existing nodes, but it first removes existing temp meta nodes for the same key and different values and then applies the node w/ the temporary modifier.

Fixes #2957

---

common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/SqlStorage.java

Previously contained "SQLite," however, SqlStorage is an abstract implementation of all Sql types.

Generify SqlStorage shutdown exception message

---

bukkit/src/main/resources/luckperms.commodore
common/src/main/java/me/lucko/luckperms/common/commands/group/DeleteGroup.java
common/src/main/java/me/lucko/luckperms/common/commands/group/GroupRename.java
common/src/main/java/me/lucko/luckperms/common/commands/misc/BulkUpdateCommand.java

This pull request brings two changes listed in #1836: [removing](#1249) and [updating](#1772) inheritance nodes.

Bulk update triggers for group related commands

---

fabric/src/main/java/me/lucko/luckperms/fabric/LPFabricPlugin.java
fabric/src/main/java/me/lucko/luckperms/fabric/event/ExecuteCommandCallback.java
fabric/src/main/java/me/lucko/luckperms/fabric/event/PreExecuteCommandCallback.java
fabric/src/main/java/me/lucko/luckperms/fabric/listeners/FabricAutoOpListener.java
fabric/src/main/java/me/lucko/luckperms/fabric/listeners/FabricOtherListeners.java
fabric/src/main/java/me/lucko/luckperms/fabric/mixin/CommandManagerMixin.java
fabric/src/main/resources/luckperms.conf
fabric/src/main/resources/luckperms.mixins.json

Also Luck please suggest a better name for `FabricOtherListeners` :joy: could not think of anything better at 2 a.m.

Implement enable-ops and auto-op on Fabric

---

common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/SqlStorage.java

Stacktrace: https://paste.gg/p/anonymous/f449339b3e684b7b910a929f6d95365dx

Fix player insert duplicate key issue with PSQL

---

bukkit/src/main/resources/luckperms.commodore
common/src/main/java/me/lucko/luckperms/common/command/spec/CommandSpec.java
common/src/main/java/me/lucko/luckperms/common/commands/group/ListGroups.java
common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/SqlStorage.java

Closes #3211
Let me know of any style changes you'd like, especially in terms of the text messages!
Sorry for the commit mess, forgot to fetch from upstream before making my edits.

Add pagination to listgroups command

---

bukkit/src/main/resources/config.yml
bungee/src/main/resources/config.yml
common/src/main/java/me/lucko/luckperms/common/commands/misc/ExportCommand.java
fabric/src/main/resources/luckperms.conf
nukkit/src/main/resources/config.yml
sponge/src/main/resources/luckperms.conf
velocity/src/main/resources/config.yml

Adds a default file name to the export command for when one isn't provided. This will resolve issue #3239

Add default file name for export command

---

fabric/build.gradle
fabric/src/main/java/me/lucko/luckperms/fabric/FabricCommandExecutor.java
fabric/src/main/java/me/lucko/luckperms/fabric/listeners/FabricConnectionListener.java

Obviously tested on a basic server.

Fabric 1.19 support

---

fabric/build.gradle
fabric/src/main/java/me/lucko/luckperms/fabric/FabricSenderFactory.java
fabric/src/main/java/me/lucko/luckperms/fabric/mixin/CommandManagerMixin.java
fabric/src/main/resources/fabric.mod.json

Update to 1.191

---

forge/gradle.properties
forge/src/main/java/me/lucko/luckperms/forge/ForgeSenderFactory.java
forge/src/main/java/me/lucko/luckperms/forge/capabilities/UserCapabilityListener.java
forge/src/main/java/me/lucko/luckperms/forge/context/ForgePlayerCalculator.java
forge/src/main/java/me/lucko/luckperms/forge/listeners/ForgeConnectionListener.java

- One minor systems change to get ParseResults, but nothing that should be breaking, and resolves a NoSuchMethod error during server init.

Forge 1.19.2

---

common/src/main/java/me/lucko/luckperms/common/backup/Exporter.java

Hey, I come with a little improvement. It should not affect backward compatibility in any way, and may have a positive impact on editor uploading speed and data usage.

Don't pretty-print exporter json (web upload)

---

fabric/src/main/java/me/lucko/luckperms/fabric/listeners/FabricPermissionsApiListener.java

Implements lucko/fabric-permissions-api#9
_(The changes in [lucko/fabric-permissions-api](https://github.com/lucko/fabric-permissions-api) have to be published before merging)_

add: Fabric offline permission check event

---

.github/workflows/ci.yml
build.gradle
bukkit-legacy/build.gradle
bukkit-legacy/loader/build.gradle
bukkit/build.gradle
bukkit/loader/build.gradle
bungee/build.gradle
bungee/loader/build.gradle
common/build.gradle
fabric/build.gradle
forge/build.gradle
forge/forge-api/build.gradle
forge/loader/build.gradle
gradle/libs.versions.toml
nukkit/build.gradle
nukkit/loader/build.gradle
settings.gradle
sponge/build.gradle
sponge/loader/build.gradle
standalone/app/build.gradle
standalone/build.gradle
standalone/loader/build.gradle
velocity/build.gradle

compiles, bukkit module works others probably do too
Also updates ansi to [1.0.1](https://github.com/KyoriPowered/ansi/releases/tag/v1.0.1)

chore: update gradle and plugins

---

common/build.gradle
common/src/main/java/me/lucko/luckperms/common/dependencies/Dependency.java
common/src/main/java/me/lucko/luckperms/common/locale/Message.java
standalone/app/build.gradle

All adventure modules should probably be updated to `4.14.0`
I can move the changes made to `Messages.java` to another PR (or not at all, since they were just deprecation warnings)
Updated a bunch of deprecated stuff to use the not deprecated stuff because... reasons?

Support for MM in meta info and fix deprecated stuff

---

sponge/src/main/java/me/lucko/luckperms/sponge/listeners/SpongeConnectionListener.java

API-11 introduced breaking changes to the `ServerSideConnectionEvent`. This PR supports them while keeping compatibility with previous API versions.

Add support for Sponge API-11

---

fabric/build.gradle
fabric/src/main/java/me/lucko/luckperms/fabric/FabricSenderFactory.java
fabric/src/main/java/me/lucko/luckperms/fabric/messaging/PluginMessageMessenger.java

I have got a working build for 1.21 Fabric running, would like to share the targeting of 1.21 for Fabric in a place where others could also target for other platforms

Updated to target 1.21 for Fabric

---

common/src/main/java/me/lucko/luckperms/common/command/CommandManager.java
common/src/main/java/me/lucko/luckperms/common/messaging/LuckPermsMessagingService.java
common/src/main/java/me/lucko/luckperms/common/model/manager/user/UserHousekeeper.java
common/src/main/java/me/lucko/luckperms/common/storage/implementation/file/watcher/FileWatcher.java
common/src/main/java/me/lucko/luckperms/common/util/ExpiringSet.java

Switches the custom ExpiringSet implementation to use a java-backed implementation from Collections with more methods implemented.

Simplify ExpiringSet implementation

---

bukkit/src/main/java/me/lucko/luckperms/bukkit/listeners/BukkitPlatformListener.java

There are not many plugins that do this, so no idea if this pr is worth it tbh
But probably more plugins that provide Vault will appear after paper hard-fork

Support plugins that provide Vault

---

bukkit/src/main/java/me/lucko/luckperms/bukkit/LPBukkitBootstrap.java
bukkit/src/main/java/me/lucko/luckperms/bukkit/LPBukkitPlugin.java
bungee/src/main/java/me/lucko/luckperms/bungee/LPBungeeBootstrap.java
common/src/main/java/me/lucko/luckperms/common/dependencies/DependencyRegistry.java

fix: Fix classExists to handle NoClassDefFoundError in Java 17
